### ISSUE TITLE
Planning and Self Admin

### ISSUE THREAD

**Issue by solomon-fibonacci** [solomon-fibonacci/blister-pack#1]
Add todo's  (as granular as possible) to each of the items here and every week, when trying to fill the time quota for that week, each todo can have another topic in the 71 lanes that it is applicable to. Lanes can be closed as needed. so e.g week 1: 7*23 hours to fill up. look at all the items I'm behind time quota on (since there's an alloted time for everything, the time quota should have a target average for each item). This is just to indicate urgency, not priority

Priority is as follows:

Priority 1: Directly related to growing Lykdat
Priority 2: Directly related to my wellbeing (e.g Emma)
Priority 3: Indirectly related to growing Lykdat

Tasks in one lane may be related to another lane so time allocation for another lane may also be used to fulfil the same objective.

When working on something, close tabs! Come back here to put maximum of 3 links that may be relevant. for you to continue next time.

Current time total: 1867
todo: 
- bring down to target of 1823
- create a way to make this into commits
- account for possibility of travelling to Germany

For the first 7 days, duplicate lanes are opportunity to add something new. e.g lane 43[changed from 'plan' to 'inburgeren'], 13

Start using labels related to other lanes/tracks etc.
When revisiting plan, time allocation may change

Revisit/Revise plans and put things in a calendar for the week

10022022
- [ ] - #2:* Read comp analysis
- [ ] - #2:* Work on finishing blog setup
- [ ] - #7: 1 Work on plan for startup school execution 
- [ ] - #2: 0.5 Respond to MAS contract
- [ ] - #2: 0.5 Respond to MAS new opportunity
- [ ] - #10: 0.5 Work on openAI setup
- [ ] - #10: 1.0 UX designer
- [ ] - #10: 0.5 Check in on OKR with team at 3pm
- [ ] - #50: 1.0 Fill out tasks related to […list business sprint topics here]
- [ ] - #41: 1.0 Groceries
- [ ] - #19: 1.0 Cook [breakfast + lunch]
- [ ] - #9: 0.2 Call with Yemi
- [ ] - #6: 1.0 Mocro Mafia with Emma
- [ ] - #43: 0.5 Gemeente call and chat with Emma
- [ ] - #28: 1.0  Read and updated the bible
- [ ] - #5: 5.0 Sleep
- [ ] - #27: 0.5 Dutch exercise
- [ ] - #14: 0.1 69 push ups

Convert these things into issues and then link it to a blisterPack repo. The blisterPack repo will be used side by side with a md editor and each subtopic will be a folder within the parent topic and the hierarchy  will continue like that. 
The aim is to be able to deploy it into a website, this is what will make up bunmioosha.com [i think].
Any new mission will just be a folder and I should be able to have a folder for "featured topics"
There should be a feature to protect some pages, or sections even

This might evolve into a project that i'll develop as a software. but for now, scrapping together tools and pointing out what I can't yet do should be enough to start with.

// Can't do
> time tracking and aggregation

What about a todo list that is a list but goes from left to right... day to day... you can either tick off or roll over. 

11022022
- [ ] - #2:* Read comp analysis
- [ ] - #2:* Work on finishing blog setup
- [ ] - #7:  Work on plan for startup school execution 
- [ ] - #10:  Work on openAI setup
- [ ] - #10:  Check in on OKR with team at 3pm
- [ ] - #19:  Cook [breakfast + dinner]
- [ ] - #28:   Read and updated the bible
- [ ] - #5:  Sleep
- [ ] - #27:  Dutch exercise
- [ ] - #14:  69 push ups
- [ ] - #2:* Ingressive capital

**Comment by solomon-fibonacci** [comment]
11022022
- [ ] - #9:* Read comp analysis
- [ ] - #9:* Work on finishing blog setup
- [ ] - #7:  Work on plan for startup school execution 
- [ ] - #10:  Work on openAI setup
- [ ] - #10:  Check in on OKR with team at 3pm
- [ ] - #19:  Cook [breakfast + dinner]
- [ ] - #28:   Read and updated the bible
- [x] - #5: 6.0  Sleep
- [ ] - #27:  Dutch exercise
- [x] - #14: 0.5 69 push ups
- [ ] - #9:* Ingressive capital
- [ ] - #8: Demo
- [x] - #2: 1.0 Watch SUS video
- [x]  - #66 : 0.5 Dishes, bed, reducing chaos
